name = "api-stealthybat"
account_id = "a74d06ef1a32cc4d76ab4566ba1b22ee"
main = "worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "batprox_data"
id = "2f71f7503e3f4bfcb52b2ea559d379df"
preview_id = "2f71f7503e3f4bfcb52b2ea559d379df"

[[d1_databases]]
binding = "batprox"
database_name = "batprox"
database_id = "97a4e391-1474-4d61-a412-8558133a0d39"

[vars]
SITE_URL = "https://stealthybat.org"

# After deploy, add custom domain api.stealthybat.org in Dashboard > Workers > api-stealthybat > Settings > Domains & Routes

[ai]
binding = "AI"
